export const pages = [
  { slug: 'index', title: '01 · The calendar · Thailand Run Sheet' },
  { slug: 'important', title: '03 · Read this part twice · Thailand Run Sheet' },
  { slug: 'before-you-fly', title: '04 · Before you fly · Thailand Run Sheet' },
  { slug: 'transport', title: '05 · Moving between places · Thailand Run Sheet' },
  { slug: 'hotels', title: '06 · Hotel guide · Thailand Run Sheet', stylesheet: '/assets/styles/hotels.css' },
  { slug: 'expenses', title: '07 · Settle up · Thailand Run Sheet' },
  { slug: 'food', title: '08 · Eating — and the pork problem · Thailand Run Sheet' },
  { slug: 'health', title: '09 · Health, and what Thai pharmacies will hand you · Thailand Run Sheet' },
  { slug: 'money', title: '10 · Money on the ground · Thailand Run Sheet' },
  { slug: 'scams', title: '11 · Scams, ranked by how often they land · Thailand Run Sheet' },
  { slug: 'unresolved', title: '12 · Still to resolve · Thailand Run Sheet' },
  { slug: 'checklist', title: '13 · Checklist · Thailand Run Sheet' },
  { slug: 'emergency', title: '14 · If something goes wrong · Thailand Run Sheet' },
  { slug: 'links', title: '15 · Links · Thailand Run Sheet' },
  { slug: 'sharing', title: '16 · Share calendar and ledger · Thailand Run Sheet' },
];
